### ISSUE TITLE
Signup and password reset?

### ISSUE THREAD

**Issue by saileshkush95** [jbittel/django-mama-cas#103]
How can i implement password rest, forget password and signup features.

**Comment by manelclos** [comment]
Hi @saileshkush95, that feature does not belong into MamaCas.

That said, look into Django itself, `django.contrib.auth`, https://github.com/django/django/blob/main/django/contrib/auth/urls.py#L16

**Comment by manelclos** [comment]
Inactive, closing. Please reopen if necessary.
