### ISSUE TITLE
build pip package please

### ISSUE THREAD

**Issue by janaki-sasidhar** [jbittel/django-mama-cas#105]
The pip package on pypi is 2 years old. Pleaes update it. Thanks in advance.

**Comment by maltemosler** [comment]
This would be very nice

**Comment by manelclos** [comment]
@janaki-sasidhar this is on the works now. Thanks for reporting.

**Comment by janaki-sasidhar** [comment]
Thanks :)

**Comment by manelclos** [comment]
Version 2.5.0 is now released and should fix this issue, please reopen if necessary.

https://pypi.org/project/django-mama-cas/
