### ISSUE TITLE
django 3.1.5 - cannot import name 'python_2_unicode_compatible' 

### ISSUE THREAD

**Issue by necholasg** [jbittel/django-mama-cas#106]
import error installing with django 3.1.5:
`cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding`

Issue:
Django 3 has removed the django.utils.encoding.python_2_unicode_compatible() api.
https://docs.djangoproject.com/en/3.0/releases/3.0/

Solution:
I only found one use, but there could be more? `mama_cas/models.py`
replace: `from django.utils.encoding import python_2_unicode_compatible`
with: `from six import python_2_unicode_compatible`

**Comment by manelclos** [comment]
@necholasg the code is fixed in master, we will release soon. Thanks for reporting and sorry for the inconvenience.

**Comment by manelclos** [comment]
Version 2.5.0 is now released and should fix this issue, please reopen if necessary.

https://pypi.org/project/django-mama-cas/
