### ISSUE TITLE
How to send attributes to the client?

### ISSUE THREAD

**Issue by d0nezer0** [jbittel/django-mama-cas#16]
I wish to know how to call the callbacks.py's funcs.

Now I use django-mama-cas as the CAS server, and django-cas-ng as a clients to login.
I need to add a user access-token to the args to the client.
I can get the token on the server side, how can I get it on the client sites?
Thanks a lot.

**Comment by jbittel** [comment]
Have you looked at the docs for [MAMA_CAS_ATTRIBUTE_CALLBACKS](http://django-mama-cas.readthedocs.org/en/latest/settings.html#django.conf.settings.MAMA_CAS_ATTRIBUTE_CALLBACKS)? That is how you specify the dotted path to a callback function, whether one of the examples in callbacks.py or a custom one you've written. When performing a /serviceValidate or /proxyValidate that will return those values in the XML success response.

**Comment by d0nezer0** [comment]
Thanks a lot. I didn't read the docs carefully. I solved it.

And now I log out my website of client A, and I can log out the server website .
How can I log out the other logged in websites?
They have the cookies whit themselves, should I call the logout function for all the logined sites?
And where should I add the code. In server site or the logout button site?

Best regards.

**Comment by d0nezer0** [comment]
I  read the code carefully, and I found the logout func deals with just the logout site.
So there is not  a logout all sites function?

**Comment by jbittel** [comment]
You're correct, CAS doesn't have direct control over those external services. You can use [MAMA_CAS_ENABLE_SINGLE_SIGN_OUT](http://django-mama-cas.readthedocs.org/en/latest/settings.html#django.conf.settings.MAMA_CAS_ENABLE_SINGLE_SIGN_OUT) to send logout requests to all authenticated services for the specific user. However, note that this only sends the request and it's up to the service to accept the information and actually do something about it. The process of configuring this will depend on each service in question.

**Comment by d0nezer0** [comment]
Thanks a million.
