### ISSUE TITLE
logout 504 Gateway Time-out

### ISSUE THREAD

**Issue by d0nezer0** [jbittel/django-mama-cas#18]
I test the django-mama-cas and django-cas-ng with my develop env, I found it all goes well.
But I run it with test env, with mama-cas with url zgxcw-sso.acttao.com and cas-ng with url http://qycs.zgxcw.com.cn/
When I logout , logout 504 Gateway Time-out happens a lot.
ususlly calls the sso server cause the time-out error.
Does it have some design faultiness?

**Comment by jbittel** [comment]
I've not been able to reproduce this issue. I set up a project with django-cas-ng and was able to successfully log in and out with no issues.

Are you only experiencing this problem on logout? Are you using the single sign-out configuration? I would double-check your django-cas-ng configuration for your LOGOUT_URL and the associated URL.

**Comment by d0nezer0** [comment]
It's the settings of  django.conf.settings.MAMA_CAS_ASYNC_CONCURRENCY
    Default:	2

    If single sign-out is enabled and gevent is installed, this setting limits the concurrency of requests sent for a logout event. If the number of requests reaches this limit, additional requests block until there is room. Setting this value to zero disables this limiting.

I set MAMA_CAS_ASYNC_CONCURRENCY = 9999 or MAMA_CAS_ASYNC_CONCURRENCY = 0
did not help the 504 .

some time logs out frequently, and some times 504. 
I installed gevent as well, but I did not use it .
gevent is the reason?

**Comment by d0nezer0** [comment]
Here is my settings:

MAMA_CAS_ALLOW_AUTH_WARN = True
MAMA_CAS_ASYNC_CONCURRENCY = 0/2/99999(I test some numbers)
MAMA_CAS_FOLLOW_LOGOUT_URL = True
MAMA_CAS_TICKET_EXPIRE = 9999
MAMA_CAS_TICKET_RAND_LEN = 32
MAMA_CAS_VALID_SERVICES = ()
# MAMA_CAS_ATTRIBUTE_CALLBACKS = ('callbacks.user_token_attributes',)
MAMA_CAS_ATTRIBUTE_CALLBACKS = ('zgxcw_sso.callbacks.user_token_attributes',)
MAMA_CAS_ENABLE_SINGLE_SIGN_OUT = True

**Comment by jbittel** [comment]
Try disabling the single sign-out and see if that makes a difference. That might help narrow down where the problem is occurring.

**Comment by d0nezer0** [comment]
You mean set MAMA_CAS_ENABLE_SINGLE_SIGN_OUT = False.?
I didn't set this at first, and the 504 happened. After I tried the logout settings,

btw,  MAMA_CAS_ENABLE_SINGLE_SIGN_OUT is True or False doesn't make any differences?
When it is True,  logs out according to the tickets, and the result is the same to False.

**Comment by jbittel** [comment]
Hmmm...it's not related to the callbacks then. Is it actually MamaCAS that's returning the timeout, or is it the logout URL that's being redirected to?

**Comment by d0nezer0** [comment]
When timeout happends, firefox shows the sso server logout url keep running, but the user has logout already.
I also thought might be the network issues.  Right ?

**Comment by jbittel** [comment]
I would agree that it's likely a network or other configuration issue that's causing this problem. I can't replicate it, and the way it's behaving makes me think the issue lies elsewhere.

If you're able to track it down more specifically to MamaCAS, feel free to reopen this ticket. Thanks!

**Comment by d0nezer0** [comment]
Sorry for I forgot to read the message. Last time I set the /etc/hosts file, and the issue disappeared.
I think we do not need to reopen this. 
And thanks for your suggestions.
