### ISSUE TITLE
use LOGIN_REDIRECT_URL if user is already logged in

### ISSUE THREAD

**Issue by manelclos** [jbittel/django-mama-cas#23]
Hi, out of curiosity, why don't you redirect to LOGIN_REDIRECT_URL here:
https://github.com/jbittel/django-mama-cas/blob/master/mama_cas/views.py#L90

I'm going to wrap LoginView just to do that, so logged in users get to the correct landing page.

**Comment by manelclos** [comment]
And also here:
https://github.com/jbittel/django-mama-cas/blob/master/mama_cas/views.py#L145

**Comment by jbittel** [comment]
I've been musing about this feature, and the main reason I'm hesitating is that it diverges from the CAS specification. I'm trying to keep those diversions to a minimum and only where they add specific value.

As SSO typically supports multiple services, the login page is typically accessed from one of those services and then redirects back to that service. I think it's a much less common use case to access the login page directly and then redirect to a landing page. Is there a reason you can't set the landing page up as a CAS service, so if the user isn't logged in they're redirected to the login page and back?

**Comment by manelclos** [comment]
Hi Jason,

In our case the login page is the entry point. When you access it we invalidate the current SSO session (we do a single sign out) for security purposes, then call mama_cas LoginView. If the landing page was a service, then the user could be still logged in.

Also, for example after password reset, you're left in the "password link sent" screen (using django-allauth along mama_cas), so the best to do there is to send the user to the login screen, we can't pass the "service" param around.

Since we are already subclassing the LoginView for the logout, we do the redirect afterwards. I see your point. I was just curious about the login screen sitting still there while the user is already logged in and django specifies that LOGIN_REDIRECT_URL is where you end up after login.
