### ISSUE TITLE
ProxyGrantingTicket security

### ISSUE THREAD

**Issue by nitmir** [jbittel/django-mama-cas#26]
Hello,
I do not see anything about ProxyGrantingTicket in https://django-mama-cas.readthedocs.org/en/latest/settings.html. Does that means that any services of MAMA_CAS_VALID_SERVICES that vavidates 
```
        1. The URL scheme must be HTTPS
        2. The SSL certificate must be valid and its name must match that
           of the service
        3. The callback URL must respond with a 200 or 3xx response code
```
can retrieve a PGT ticket ?

This would mean that letting mama-cas open is a major security leak as anyone would then be able to fetch a PGT to emit ProxyTicket.

If pgturl are not validated agains MAMA_CAS_VALID_SERVICES (I do not see pgturl checked against is_valid_service_url but I can have missed it) that means anyone can always retrieve a PGT.

**Comment by nitmir** [comment]
Indeed no checking are done on pgtUrl. By only allowing one service on ```MAMA_CAS_VALID_SERVICES``` I was able to retrive a PGT ticket without controling that service.

This is a major security issue.

Let assume : 
```
MAMA_CAS_VALID_SERVICES=('^https://A$')
```
 1. login to https://cas/login?service=https://A
 1. intercept the redirection and note the service ticket ST-truc
 1. call https://cas/serviceValidate?service=https://A&ticket=ST-truc&pgtUrl=https://controled.server/
 1. PGT is send to https://controled.server/

**Comment by jbittel** [comment]
I agree, the PGT URL validation ought to check against MAMA_CAS_VALID_SERVICES. I'll work up a fix for that.

Thanks!
