### ISSUE TITLE
Valid services stored in database

### ISSUE THREAD

**Issue by lukacu** [jbittel/django-mama-cas#32]
What I miss with the current implementation is that valid services have to be defined in the settings file. Would an option to store services in the database so that they can be reconfigured more easily violate the design of the app? I can do the modifications, but I would like to know in advance if the idea is conceptually acceptable.

**Comment by jbittel** [comment]
That's a good question. I've considered that idea before, but went with the current design for speed and simplicity. However, I can see where it would be helpful in many situations to not have to redeploy to update valid services. The main simplicity benefit is that the current method requires no UI outside of the login interface itself. Are you thinking of using the admin interface for this?

I'm also in the process of reworking the services configuration, allowing more information to be specified for each service including allowing/disallowing proxy authentication, enabling/disabling SLO and configuring a SLO URL. I'm hoping to have time to finish that up soonish, but that would likely impact the design of something like this.

Thanks!

**Comment by jbittel** [comment]
This was a long time coming, but was fully landed in #43. Custom service backends can now be configured, so this can be easily developed without needing to be hard-coded in the design of the app. Plus, it can be combined with other service backends if necessary, allowing for multiple sources or fall-back defaults.
