### ISSUE TITLE
Allow for custom login templates

### ISSUE THREAD

**Issue by lorenmh** [jbittel/django-mama-cas#38]
Currently the login template is hardcoded into the LoginView class.

Were I to submit a PR for this, would it be reviewed?

**Comment by jbittel** [comment]
I'm certainly interested in better ways of handling templates. How are you thinking this would be implemented? Note that the WarnView class also has a template path specified.

Thanks!

**Comment by lorenmh** [comment]
I've just put in a pull request, I've implemented it in a dead simple way, is this satisfactory?

**Comment by jbittel** [comment]
Looks good, thanks for the PR!
