### ISSUE TITLE
Can django-mama-cas just use gevent socket patch?

### ISSUE THREAD

**Issue by bluven** [jbittel/django-mama-cas#40]
I encountered this error "child watchers are only available on the default loop" yesterday, after debugging i found it was caused by gevent subprocess patch.  After reading django-mama-cas, i found this piece code:

```
if gevent:
    from gevent.pool import Pool
    from gevent import monkey
    monkey.patch_all(thread=False, select=False)
```

This piece  patches subprocess module by default and i found this 

> On POSIX platforms, this module is not usable from native threads other than the main thread; attempting to do so will raise a TypeError.

at [http://www.gevent.org/gevent.subprocess.html](http://www.gevent.org/gevent.subprocess.html).

I think if django-mama-cas only gevent socket patch, it might be more safe and wise to use the patches as needed.

**Comment by jbittel** [comment]
This has come up before, and it seems the gevent monkey patching is problematic in several different contexts. I've just pushed up 88aa958 that replaces gevent with requests-futures. Please give it a try and see if it resolves the issue for you. It appears to work, but I haven't had much time to test it.

Thanks!
