### ISSUE TITLE
What is the different configure between server and client?Thx.

### ISSUE THREAD

**Issue by gwenxia** [jbittel/django-mama-cas#47]
Have any demo project which is based django-mama-cas to show how to integrate django-mama-cas to actual project?Thx!

**Comment by manelclos** [comment]
Hi @gwenxia, a bit late, but here is a demo project with one server and two clients that shows SSO and SLO. This was used for another issue so it is not super-clean:

https://github.com/manelclos/django-cas-test

**Comment by manelclos** [comment]
Inactive, closing. Please reopen if necessary.
