### ISSUE TITLE
about single logout

### ISSUE THREAD

**Issue by diegoduncan21** [jbittel/django-mama-cas#48]
I'm using MAMA_CAS and MAMA_CAS_NG, I want to log out from all services when I log out from the primary server.
I have this configuration in a primary server for MAMA_CAS:
```
MAMA_CAS_SERVICES = [
    {
        'SERVICE': '^https://[^\.]+\.example\.com',
        'LOGOUT_ALLOW': True,
        'LOGOUT_URL': 'https://www.example.com/logout',
    }
]
```
when I go to /logout in primary server, it automatically sends a post to service URL configured in LOGOUT_URL, but it goes with POST request (in this line: https://github.com/jbittel/django-mama-cas/blob/master/mama_cas/models.py#L255), and  MAMA_CAS_NG expects a GET request. Then it throws me `Method Not Allowed (POST): /logout/`.
The logout from service is working ok, it allows log out from all sites.

**Comment by pmayer** [comment]
django_cas_ng handles logout requests in callback view (https://github.com/mingchen/django-cas-ng/blob/master/django_cas_ng/views.py#L145). You should change the LOGOUT_URL parameter accordingly.

**Comment by diegoduncan21** [comment]
Thank you, i enable this url `url(r'^accounts/callback$', django_cas_ng.views.callback, name='cas_ng_proxy_callback'),` and change `LOGOUT_URL` pointing there and works.
