### ISSUE TITLE
Documentation links to CAS protocol broken

### ISSUE THREAD

**Issue by godlike64** [jbittel/django-mama-cas#57]
The following section of the documentation contains links to a third-party detailing the protocol:

http://django-mama-cas.readthedocs.io/en/latest/protocol.html

However, none of these appear to work. Additionally, there's no link to the CAS 3.0 protocol, so it would be nice if that could be added.

**Comment by manelclos** [comment]
@godlike64, please see PR #61, do you have links for CAS 1/2/3 protocols?

**Comment by godlike64** [comment]
@manelclos I think it would maybe be https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol-Specification.html ? Full specification for all versions 1, 2 and 3.

**Comment by manelclos** [comment]
Ok, I'll use the parent page which talks about the protocol and its specifications. CAS-Protocol-Specification.html includes CAS 2.0, but in the parent page they have a link dedicated to version 2.0.

https://apereo.github.io/cas/5.2.x/protocol/CAS-Protocol.html

Thanks!

**Comment by manelclos** [comment]
PR https://github.com/jbittel/django-mama-cas/pull/61 has been merged.
