### ISSUE TITLE
Django 2.0+python3.6 import error 

### ISSUE THREAD

**Issue by paulwinex** [jbittel/django-mama-cas#62]
Try to start default django2 project with mama-cas and minimal settings.

```
File ".../python3.6/site-packages/mama_cas/models.py", line 32, in <module>
from mama_cas.utils import add_query_params
File ".../python3.6/site-packages/mama_cas/utils.py", line 5, in <module>
from django.core import urlresolvers
ImportError: cannot import name 'urlresolvers'
```

Need to change imports

```
# from django.core import urlresolvers
from django import urls as urlresolvers
```

**Comment by manelclos** [comment]
Please use master branch until next release

**Comment by riodw** [comment]
How to import with GitHub:
`pip install -e git+https://github.com/jbittel/django-mama-cas.git#egg=django_mama_cas`

**Comment by jbittel** [comment]
The new version has been released with compatibility for recent versions of Django. Thanks!
