### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by manelclos** [jbittel/django-mama-cas#63]
We should create a new release and push it to pypi.

#62

**Comment by klem4** [comment]
waiting for release, thx!

**Comment by andredalle** [comment]
Django 2.0 support requires recent updates which means not being able to rely on a pip requirements.txt - which is not great for production CAS deployments.

Works great though.

**Comment by manelclos** [comment]
Hi @andredalle,

You can still install it using pip with:
```
pip install -e git+https://github.com/jbittel/django-mama-cas.git#egg=django-mama-cas
```

That will appear in your requirements.txt as:
```
-e git+https://github.com/jbittel/django-mama-cas.git@b820306c182879d70d2470d4882b911ab5fc01fc#egg=django_mama_cas
```

And of course you can remove the commit reference to always use the latest version available:
```
-e git+https://github.com/jbittel/django-mama-cas.git#egg=django_mama_cas
```

**Comment by andredalle** [comment]
I didn't check that that works with python2, and I don't know that it's a good idea to change the behaviour on returning user attributes; could break existing CAS deployments.  However this seems like sensible list behaviour to me.

**Comment by rinti** [comment]
Any status on this? Would be greatly appreciated.

**Comment by manelclos** [comment]
@jbittel anything I can do to make this happen?

**Comment by Moonsownner** [comment]
sry, if i use pip install -e git+https://github.com/jbittel/django-mama-cas.git#egg=django-mama-cas to install it. I failed to add 'mama_cas' to INSTALLED_APPS, how can i solve this problem

**Comment by manelclos** [comment]
@Moonsownner what is the error you are getting? can you share more details about the problem?

**Comment by Moonsownner** [comment]
@manelclos if use #egg to install the package. I get a 'src' folder in my project root, and the mama_cas files are in this folder. But i don't  have mama_cas package in my site-packages. So how to link mama_cas into INSTALLED_APPS?

**Comment by jbittel** [comment]
Finally! I got an environment reconfigured that allowed me to publish this new version. Thanks for the patience!
