### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by pmayer** [jbittel/django-mama-cas#88]
Hi @jbittel,

there hasn't been a new release for a year, so I just wanted to ask if this project is still active?

Regards,
Philipp

**Comment by RonsenbergVI** [comment]
Wondering the same. Does anyone know if the project is still active?

**Comment by manelclos** [comment]
@pmayer I'd say it is, but yes, a release would be awesome. I think the release process should be documented and someone else should also be able to produce releases, like in many other projects I help with.

**Comment by pmayer** [comment]
@manelclos Are you really sure it is? Latest commit is from Feb 7, 2019.

**Comment by manelclos** [comment]
@pmayer yeah, we need to push some updates, but no major problems have been reported. This is on my list, just need some free time :)

**Comment by pmayer** [comment]
@manelclos would it be at least possible to push the latest master to pypi? We need the "list" change and have to install it via github at the moment.

**Comment by lidongok** [comment]
go on!  This project really nice ~

**Comment by manelclos** [comment]
@pmayer will arrive soon now.

**Comment by pmayer** [comment]
@manelclos great to hear 🙂

**Comment by manelclos** [comment]
Finally :)

Version 2.5.0 is now released and should fix this issue, please reopen if necessary.

https://pypi.org/project/django-mama-cas/
